definitions:
  domain.RiderRequest:
    properties:
      coordinates:
        items:
          type: number
        type: array
      id:
        type: string
      radius:
        type: number
      type:
        type: string
    required:
    - coordinates
    - radius
    - type
    type: object
  domain.RiderResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /handle-rider:
    post:
      consumes:
      - application/json
      description: Handle rider requests and communicate with the Driver Location
        API
      operationId: rider-handler
      parameters:
      - description: Rider request object
        in: body
        name: riderRequest
        required: true
        schema:
          $ref: '#/definitions/domain.RiderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.RiderResponse'
swagger: "2.0"
